spring:

  main:
    web-application-type: reactive

  application:
    name: GATEWAY-MODULE
    
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: patient-details
          uri: http://localhost:8081/demographic_details
          predicates:
          - Path=/demographic_details/**
        - id: visit-detailss
          uri: http://localhost:8082/visit_details
          predicates:
          - Path=/visit_details/**
          
      
    
server:
  port: 7000
  
eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
   instance:
      hostname: localhost
      

